kookmin-sw/capstone-2025-08

- ai/.dockerignore
- ai/.gitignore
- ai/app.py
- ai/main.py
- Closes #14 
모델 서버 초기 세팅을 진행하였습니다. (fastapi, gitignore, dockerignore)
> [ BE ] chore/#14 모델 서버 초기 세팅

- ai/config.py
- ai/core/sqs.py
- ai/main.py
- Closes #16 
- AWS SQS 메시지 큐 연동
- 백그라운드 스케줄러를 통해 주기적으로 SQS 메시지를 수신하도록 구현
- 메시지 처리 완료 후 SQS에서 삭제
- `.env` 설정 기반으로 SQS 관련 정보(AWS_REGION_NAME, QUEUE_URL 등) 주입
- 작업 진행 로깅 추가
- 테스트용 메시지큐 메시지 추가 API 추가
> [ BE ] feat/#16 모델 서버 SQS 연동

- backend/.github/workflows/ci-cd.yml
- backend/Dockerfile
> #13 
> 
- EC2 배포 완료 및 Mysql docker image로 실행 완료 (43.201.166.43) mysql 8.0.32
- backend/main에 배포시 ci-cd 워크플로우 실행 (추후 app-main으로 변경 가능)
>
> [ BE ] chore/#13 스프링 서버 배포 및 CI/CD 파이프라인 구축

- backend/src/main/java/site/pathos/domain/annotation/cellAnnotation/entity/TissueAnnotation.java
- backend/src/main/java/site/pathos/domain/annotation/tissueAnnotation/entity/CellAnnotation.java
- backend/src/main/java/site/pathos/domain/annotationHistory/entity/AnnotationHistory.java
- backend/src/main/java/site/pathos/domain/comment/entity/Comment.java
- backend/src/main/java/site/pathos/domain/dataSet/entity/DataSet.java
- backend/src/main/java/site/pathos/domain/dataSet/entity/DataType.java
- backend/src/main/java/site/pathos/domain/inferenceHistory/entity/InferenceHistory.java
- backend/src/main/java/site/pathos/domain/model/entitiy/Model.java
- backend/src/main/java/site/pathos/domain/project/entity/Project.java
- backend/src/main/java/site/pathos/domain/roi/entity/Roi.java
- backend/src/main/java/site/pathos/domain/sharedProject/entity/SharedProject.java
- backend/src/main/java/site/pathos/domain/subProject/SubProject.java
- backend/src/main/java/site/pathos/domain/user/entity/User.java
- backend/src/main/java/site/pathos/domain/userModel/entity/UserModel.java
> -close #19 
ERD를 기반으로 하여 Entitiy를 작성하였습니다.
```
src
└── main
└── java
└── com.pathos
├── domain
│   ├── annotation
│   │   └── entity
│   │       ├── CellAnnotation.java
│   │       └── TissueAnnotation.java
│   ├── annotationhistory
│   │   └── entity
│   │       └── AnnotationHistory.java
│   ├── cellannotation
│   │   └── entity
│   ├── comment
│   │   └── entity
│   ├── dataset
│   │   └── entity
│   ├── inference
│   │   └── entity
│   │       └── InferenceHistory.java
│   ├── model
│   │   └── entity
│   │       └── Model.java
│   ├── roi
│   │   └── entity
│   │       └── Roi.java
│   ├── sharedproject
│   │   └── entity
│   ├── subproject
│   │   └── entity
│   ├── tissueannotation
│   │   └── entity
│   ├── user
│   │   └── entity
│   │ …
```
> [ BE ] feat/#19  Entity 클래스 생성

- backend/build.gradle
- backend/src/main/java/site/pathos/PathosApplication.java
- backend/src/main/java/site/pathos/global/aws/s3/AmazonS3Configuration.java
- backend/src/main/java/site/pathos/global/aws/s3/AwsProperty.java
- backend/src/main/java/site/pathos/global/aws/s3/S3Service.java
- Closes #32 
- Aws Property 클래스를 통한 AWS 설정값 주입
- S3 관련 설정( s3, presigner)
- S3 업로드 및 presigned ulr 로직 구현
> AWS property를 활용한 방식에 대한 피드백 부탁드립니다. 특히 PostConstruct를 활용한 구조가 오히려 복잡해지는지 리뷰 부탁드립니다.
> [ BE ] feat/#32 s3 관련 설정 및 로직 구현

- backend/build.gradle
- backend/src/main/java/site/pathos/domain/project/entity/Project.java
- Closes #44 #32 
- Project의 updateAt 필드명이 created_at으로 오기입된 부분을 수정하였습니다.
- s3 async client 실행을 위한 aws crt 의존성을 auth-crt로 변경하여 빌드
>
> [ BE ] fix/#44 빌드 관련 오류 수정

- backend/build.gradle
- backend/src/main/java/site/pathos/domain/annotation/cellAnnotation/dto/CellDetail.java
- backend/src/main/java/site/pathos/domain/annotation/tissueAnnotation/entity/AnnotationType.java
- backend/src/main/java/site/pathos/domain/annotation/tissueAnnotation/entity/TissueAnnotation.java
- backend/src/main/java/site/pathos/domain/annotation/tissueAnnotation/repository/TissueAnnotationRepository.java
- backend/src/main/java/site/pathos/domain/annotation/tissueAnnotation/service/TissueAnnotationService.java
- backend/src/main/java/site/pathos/domain/annotationHistory/repository/AnnotationHistoryRepository.java
- backend/src/main/java/site/pathos/domain/model/entitiy/Model.java
- backend/src/main/java/site/pathos/domain/modelServer/controller/ModelServerController.java
- backend/src/main/java/site/pathos/domain/modelServer/dto/request/RoiPayload.java
- backend/src/main/java/site/pathos/domain/modelServer/dto/request/TrainingRequestDto.java
- backend/src/main/java/site/pathos/domain/modelServer/entity/ModelRequestType.java
- backend/src/main/java/site/pathos/domain/modelServer/service/ModelServerService.java
- backend/src/main/java/site/pathos/domain/roi/controller/RoiController.java
- backend/src/main/java/site/pathos/domain/roi/dto/request/RoiDetail.java
- backend/src/main/java/site/pathos/domain/roi/dto/request/RoiPayload.java
- backend/src/main/java/site/pathos/domain/roi/dto/request/RoiSaveRequestDto.java
- backend/src/main/java/site/pathos/domain/roi/entity/Roi.java
- backend/src/main/java/site/pathos/domain/roi/repository/RoiRepository.java
- backend/src/main/java/site/pathos/domain/roi/service/RoiService.java
- backend/src/main/java/site/pathos/domain/subProject/SubProject.java
- backend/src/main/java/site/pathos/global/aws/config/AwsCredentialsConfig.java
- backend/src/main/java/site/pathos/global/aws/config/AwsProperty.java
- backend/src/main/java/site/pathos/global/aws/s3/AmazonS3Configuration.java
- backend/src/main/java/site/pathos/global/aws/s3/S3Service.java
- backend/src/main/java/site/pathos/global/aws/sqs/config/SqsConfig.java
- backend/src/main/java/site/pathos/global/aws/sqs/dto/request/TrainingRequestDto.java
- backend/src/main/java/site/pathos/global/aws/sqs/service/SqsService.java
- Closes #48 
- aws sqs 연동
- roi에서 연관된 annotation History정보들을 불러올수 있도록 수정
- 학습 + 추론 로직 구현
>
> [ BE] feat/#48 학습 요청 로직 구현

- .github/workflows/ci-cd.yml
- backend/src/main/java/site/pathos/global/config/WebConfig.java
- Closes #65 
Webconfig를 통해 임시로 localhost:3000 에 대한 cors를 허용합니다.
- 이후에 SpringSecurity를 적용하게되면 해당 설정은 삭제할 예정입니다.
- 원활한 배포를 위해 배포 대상 브렌치를 app-develop으로 변경하였습니다.
>
> [BE] chore/#65 cors 임시 설정

- ai/config.py
- ai/core/image_processor.py
- ai/core/sqs.py
- ai/requirements.txt
- Closes #56 
- 추론으로 생성한 모델 중에 마지막으로 생성한 모델이 아닌 best 모델을 업로드하게끔 수정
- 추론 완료 후에 페이로드 정보와 함께 응용 서버 호출을 통해 완료됨을 알림
- 환경 변수 파일을 통해 응용 서버 주소와 토큰 설정
- AWS SQS에서 메시지를 받을때 WaitTimeSeconds을 걸어 성능 최적화
- requirements.txt 추가
> [ BE ] feat/#56 모델 서버 추론 완료 후 응용 서버 호출 기능 추가

- ai/.dockerignore
- ai/.gitignore
- ai/Dockerfile
- ai/config.py
- ai/core/image_processor.py
- ai/core/sqs.py
- ai/requirements.txt
- Closes #80 
- DockerFile 생성
- dockerignore 수정
- gitignore 수정
> [ BE ] feat/#80 모델 서버 도커 설정

- backend/build.gradle
- backend/src/main/java/site/pathos/domain/project/controller/ProjectController.java
- backend/src/main/java/site/pathos/domain/project/dto/request/CreateProjectRequestDto.java
- backend/src/main/java/site/pathos/domain/project/entity/Project.java
- backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
- backend/src/main/java/site/pathos/domain/subProject/entity/SubProject.java
- backend/src/main/java/site/pathos/domain/user/repository/UserRepository.java
- backend/src/main/java/site/pathos/global/aws/s3/S3Service.java
- backend/src/main/java/site/pathos/global/aws/s3/dto/S3UploadFileDto.java
- backend/src/main/java/site/pathos/global/config/AsyncConfig.java
- backend/src/main/java/site/pathos/global/config/ImageUploadExecutorConfig.java
- Closes #82 
- 프로젝트 생성
- 엔티티에 thumbnailImageUrl 필드 삭제
- 서브 프로젝트 생성
- 어노테이션 히스토리 생성
- Async 어노테이션과 S3AsyncClient를 이용한 이미지 비동기 업로드
> [ BE ] feat/#82 프로젝트 생성 기능 추가

- backend/src/main/java/site/pathos/domain/project/controller/ProjectController.java
- backend/src/main/java/site/pathos/domain/project/dto/request/UpdateProjectRequestDto.java
- backend/src/main/java/site/pathos/domain/project/entity/Project.java
- backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
- Closes #97 
- 프로젝트 제목 및 설명 수정 API 구현
- soft delete를 이용한 프로젝트 삭제 API 구현
> [ BE ] feat/#97 프로젝트 수정 및 삭제 기능 추가

- backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
- backend/src/main/java/site/pathos/domain/subProject/dto/response/SubProjectSummaryDto.java
- backend/src/main/java/site/pathos/domain/subProject/repository/SubProjectRepository.java
- backend/src/main/java/site/pathos/domain/subProject/service/SubProjectService.java
- backend/src/main/java/site/pathos/global/aws/s3/AmazonS3Configuration.java
- backend/src/main/java/site/pathos/global/error/ErrorCode.java
- Closes #118 
1. 현재 이미지 업로드 완료 여부는 boolean 타입으로 완료 여부만 체크 가능합니다
- 해당 기능은 이후에 ENUM으로 (진행중, 완료, 실패)와 같이 확장을 고려중입니다.
2. 프로젝트 당 업로드가 완료된 서브프로젝트의 비율로 업로드 진행율을 체크 가능합니다
3. 최근 커밋에 작성된 TODO는 다음 이슈에서 작업할 예정이며 작업 내용이 생각보다 클 것 같아 이슈를 분리하였습니다.
>
> [ BE ] feat/#118 이미지 업로드 상태 체크 및 진행율 확인

- backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
> [ BE ] hotfix/#120 project detail 썸네일 이미지 Presigned 적용

- backend/src/main/java/site/pathos/domain/project/repository/ProjectRepository.java
- backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
- Closes #138 
- 프로젝트 정렬 jpa 쿼리문 수정했습니다.
> [BE] fix: 프로젝트 정렬 기능 버그 수정

- backend/src/main/java/site/pathos/domain/annotation/controller/AnnotationController.java
- backend/src/main/java/site/pathos/domain/annotation/dto/request/RoiLabelSaveRequestDto.java
- backend/src/main/java/site/pathos/domain/annotation/dto/response/AnnotationHistoryResponseDto.java
- backend/src/main/java/site/pathos/domain/annotation/dto/response/GetProjectAnnotationResponseDto.java
- backend/src/main/java/site/pathos/domain/annotation/dto/response/RoiResponsePayload.java
- backend/src/main/java/site/pathos/domain/annotation/repository/AnnotationHistoryRepository.java
- backend/src/main/java/site/pathos/domain/annotation/repository/ProjectLabelRepository.java
- backend/src/main/java/site/pathos/domain/annotation/service/AnnotationService.java
- backend/src/main/java/site/pathos/domain/model/dto/TrainingResultRequestDto.java
- backend/src/main/java/site/pathos/domain/model/repository/ProjectModelRepository.java
- backend/src/main/java/site/pathos/domain/model/service/ModelServerService.java
- backend/src/main/java/site/pathos/domain/project/dto/response/SubProjectSummaryDto.java
- backend/src/main/java/site/pathos/domain/project/entity/ProjectLabel.java
- backend/src/main/java/site/pathos/domain/project/service/ProjectService.java
- Closes #152 
1. 프로젝트 조회 시 프로젝트 모델을 불러오는 쿼리에 있던 오류를 수정하였습니다.
2. 프로젝트 조회 시 dzi 이미지 제공
3. 프로젝트 라벨에 createdAt, displayOrder 제공
4. 프로젝트 저장 시 히스토리 조회 데이터 응답 추가
5. tissuePath변수명 오류 수정
>
> [ BE ] feat/#152 어노테이션 api 수정

- backend/src/main/java/site/pathos/domain/annotation/repository/ModelProjectLabelRepository.java
> [BE] fix: ModelProjectLabelRepository 수정 오류 롤백

- backend/src/main/java/site/pathos/domain/annotation/dto/request/RoiLabelSaveRequestDto.java
- backend/src/main/java/site/pathos/domain/annotation/entity/Roi.java
- backend/src/main/java/site/pathos/domain/annotation/service/AnnotationService.java
- backend/src/main/java/site/pathos/domain/annotation/service/TissueAnnotationService.java
- backend/src/main/java/site/pathos/domain/sharedProject/entity/DataSet.java
- Closes #158 
새로운 roi 및 라벨을 저장하는 과정에서 id값을 null로 처리하던 부분을 프론트에서 이슈로 인해 음수로 받도록 하였습니다.
>
> [ BE ] fix/#158 roi 및 label 저장로직 수정

- backend/src/main/java/site/pathos/domain/sharedProject/dto/response/GetSharedProjectDetailResponseDto.java
- backend/src/main/java/site/pathos/domain/sharedProject/entity/SharedProject.java
- backend/src/main/java/site/pathos/domain/sharedProject/service/PublicSpaceService.java
- Closes #177 
> 공유 프로젝트 상세 조회에 프로젝트 ID를 추가한다.
> [BE] refactor: 공유 프로젝트 상세 조회에 프로젝트 ID 추가

- frontend/src/components/annotation/annotation-header/index.tsx
> [ FE ] feat/#183 어노테이션 저장, 트레인 함수 롤백

- frontend/src/components/annotation/annotation-subproject-slider/index.tsx
- frontend/src/components/projects/subproject-table/index.tsx
> [FE] fix: 이미지 최적화 Off

- frontend/src/components/annotation/annotation-header/index.tsx
> [FE] fix: 자동 다운로드 기능 제거
